%YAML:1.0

BaseConfig:
  minDetectorConfidence: 0   # If the confidence of a detector bbox is lower than this, then it won't be considered for tracking

TargetManagement:
  maxTargetsPerStream: 150  # Max number of targets to track per stream. Recommended to set >10. Note: this value should account for the targets being tracked in shadow mode as well. Max value depends on the GPU memory capacity

  # [Creation & Termination Policy]
  minIouDiff4NewTarget: 0.5   # If the IOU between the newly detected object and any of the existing targets is higher than this threshold, this newly detected object will be discarded.
  minTrackerConfidence: 0.2   # If the confidence of an object tracker is lower than this on the fly, then it will be tracked in shadow mode. Valid Range: [0.0, 1.0]
  probationAge: 3 # If the target's age exceeds this, the target will be considered to be valid.
  maxShadowTrackingAge: 150   # Max length of shadow tracking. If the shadowTrackingAge exceeds this limit, the tracker will be terminated.
  earlyTerminationAge: 1   # If the shadowTrackingAge reaches this threshold while in TENTATIVE period, the the target will be terminated prematurely.

TrajectoryManagement:
  useUniqueID: 0   # Use 64-bit long Unique ID when assignining tracker ID.
  enableReAssoc: 1    # Enable Re-Assoc

  # [Re-Assoc: Motion-based]
  minTrajectoryLength4Projection: 20  # min trajectory length required to make projected trajectory
  prepLength4TrajectoryProjection: 10 # the length of the trajectory during which the state estimator is updated to make projections
  trajectoryProjectionLength: 300      # the length of the projected trajectory

  # [Re-Assoc: Trajectory Similarity]
  minTrackletMatchingScore: 0.2       # min tracklet similarity score for matching in terms of average IOU between tracklets
  maxAngle4TrackletMatching: 180       # max angle difference for tracklet matching [degree]
  minSpeedSimilarity4TrackletMatching: 0.4    # min speed similarity for tracklet matching
  minBboxSizeSimilarity4TrackletMatching: 0.2 # min bbox size similarity for tracklet matching
  maxTrackletMatchingTimeSearchRange: 500      # the search space in time for max tracklet similarity

DataAssociator:
  dataAssociatorType: 0 # the type of data associator among { DEFAULT= 0 }
  associationMatcherType: 0 # the type of matching algorithm among { GREEDY=0, GLOBAL=1 }
  checkClassMatch: 1  # If checked, only the same-class objects are associated with each other. Default: true

  # Thresholds in matching scores to be considered as a valid candidate for matching
  minMatchingScore4Overall: 0.0   # Min total score
  minMatchingScore4SizeSimilarity: 0.2  # Min bbox size similarity score
  minMatchingScore4Iou: 0.0       # Min IOU score
  thresholdMahalanobis: 9.4877    # Max Mahalanobis distance based on Chi-square probabilities

StateEstimator:
  stateEstimatorType: 2  # the type of state estimator among { DUMMY=0, SIMPLE=1, REGULAR=2 }

  # [Dynamics Modeling]
  noiseWeightVar4Loc: 0.05  # weight of process and measurement noise for bbox center; if set, location noise will be proportional to box height
  noiseWeightVar4Vel: 0.00625  # weight of process and measurement noise for velocity; if set, velocity noise will be proportional to box height
  useAspectRatio: 1 # use aspect ratio in Kalman filter's observation


ReID:
  reidType: 1 # the type of reid among { DUMMY=0, DEEP=1 }
  batchSize: 100 # batch size of reid network
  workspaceSize: 1000 # workspace size to be used by reid engine, in MB
  reidFeatureSize: 128 # size of reid feature
  reidHistorySize: 100 # max number of reid features kept for one object
  inferDims: [128, 64, 3] # reid network input dimension CHW or HWC based on inputOrder
  inputOrder: 1 # reid network input order among { NCHW=0, NHWC=1 }
  colorFormat: 0 # reid network input color format among {RGB=0, BGR=1 }
  networkMode: 1 # reid network inference precision mode among {fp32=0, fp16=1, int8=2 }
  offsets: [0.0, 0.0, 0.0]  # array of values to be subtracted from each input channel, with length equal to number of channels
  netScaleFactor: 1.0 # # scaling factor for reid network input after substracting offsets
  inputBlobName: "images" # reid network input layer name
  outputBlobName: "features" # reid network output layer name
  uffFile: "/home/alx/vehicle_tracking_deepstream/models/mars-small128.uff" # ABSOLUTE path to reid network uff model
  modelEngineFile: "/home/alx/vehicle_tracking_deepstream/models/mars-small128.uff_b100_gpu0_fp16.engine" # engine file path
  keepAspc: 1 # whether to keep aspc ratio when resizing input objects for reid
